
POST  http://localhost:8080/api/user/register
Content-type: application/json

{
      "email": "admin@gmail.com",
      "password": "123456",
      "firstName":"Thong",
      "lastName": "Ton",
      "address": "viet nam",
      "phoneNumber": "0123123123",
      "gender": 0,
      "roleId": "1"
}

